version: '3'

services:
  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    volumes:
      - ./source:/var/www

  nginx:
    image: nginx:alpine
    volumes:
    - ./config/nginx:/etc/nginx/conf.d
    - ./source:/var/www
    ports:
      - 80:80
      - 443:443

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecurepassword
